apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
data:
  {{- toYaml .Values.env | nindent 2 }}
  OPENAI_API_KEY: {{ .Values.openaiApiKey | quote }}
  OPENAI_ORGANIZATION: {{ .Values.openaiOrganization | quote }}
  CELERY_BROKER_URL: {{ .Values.brokerUrl | quote }}
  CELERY_ACKS_LATE: "True"
  CELERY_WORKER_PREFETCH_MULTIPLIER: "1"
