apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
data:
  {{- toYaml .Values.env | nindent 2 }}
  OPENAI_API_KEY: {{ .Values.openaiApiKey | quote }}
  OPENAI_ORGANIZATION: {{ .Values.openaiOrganization | quote }}
  SLACK_BOT_USER_ID: {{ .Values.slackBotUserId | quote }}
