apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
data:
  {{- toYaml .Values.env | nindent 2 }}
  OPENAI_API_KEY: {{ .Values.openaiApiKey | quote }}
  SLACK_BOT_TOKEN: {{ .Values.slackBotToken | quote }}
  SLACK_APP_TOKEN: {{ .Values.slackAppToken | quote }}
