apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
data:
  {{- toYaml .Values.env | nindent 2 }}
  OPENAI_API_KEY: {{ .Values.openaiApiKey | quote }}
  SERPAPI_API_KEY: {{ .Values.serpapiApiKey | quote }}
  PINECONE_API_KEY: {{ .Values.pineconeApiKey | quote }}
  PINECONE_ENV: {{ .Values.pineconeEnv | quote }}
  SLACK_BOT_TOKEN: {{ .Values.slackBotToken | quote }}
  SLACK_APP_TOKEN: {{ .Values.slackAppToken | quote }}
  PINECONE_INDEX: {{ .Values.pineconeIndex | quote }}
