apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
data:
  {{- toYaml .Values.env | nindent 2 }}
  FLOWER_BROKER_API: {{ .Values.brokerUrl | quote }}
  CELERY_BROKER_URL: {{ .Values.brokerUrl | quote }}
