# Service Configuration
# This configuration file defines a LoadBalancer service.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "flower.fullname" . }}
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5555
  selector:
    app: celery-flower
