name: Continuous Integration with Python

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Lint with Pylint
      run: make lint

    - name: Check Code Style with isort and black
      run: make code-style

    - name: Type Check with Mypy and Pyright
      run: make type-check

    - name: Run Unit Tests
      run: make test
