name: Build and Deploy to GKE

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: discord-bots
  GKE_ZONE: us-central1
  IMAGE: slack-bot
  OPENAI_ORGANIZATION: org-kJ1nkbOSvAO5nCTrJmY3Nm4x
  BROKER_URL: amqp://alola:password@rabbitmq.default.svc.cluster.local:5672

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Authentication via credentials json
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker to use gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

    # Get the GKE credentials so we can deploy to the cluster
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Deploy bot ID A05UJV11ZUM
      run: |-
        helm upgrade slack-bot ./charts/bot \
          --install \
          --atomic \
          --wait \
          --namespace a05ujv11zum \
          --create-namespace \
          --timeout 20m0s \
          --set image=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA \
          --set openaiApiKey=${{ secrets.OPENAI_API_KEY }} \
          --set openaiOrganization=$OPENAI_ORGANIZATION \
          --set slackBotUserId=U05UF7ZJ9SS \
          --debug
        kubectl get services -o wide -n a05ujv11zum

    - name: Deploy bot ID U060YNQLWAJ
      run: |-
        helm upgrade slack-bot ./charts/bot \
          --install \
          --atomic \
          --wait \
          --namespace u060ynqlwaj \
          --create-namespace \
          --timeout 20m0s \
          --set image=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA \
          --set openaiApiKey=${{ secrets.OPENAI_API_KEY }} \
          --set openaiOrganization=$OPENAI_ORGANIZATION \
          --set slackBotUserId=U060YNQLWAJ \
          --debug
        kubectl get services -o wide -n u060ynqlwaj

    - name: Set up Helm
      run: |-
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update

    - name: Deploy RabbitMQ with external access
      run: |-
        helm upgrade --install rabbitmq bitnami/rabbitmq \
          --set auth.username=alola \
          --set auth.password=password \
          --set service.type=LoadBalancer

    - name: Deploy Celery Worker
      run: |-
        helm upgrade --install celery-worker ./charts/celery \
          --set image=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA \
          --set openaiApiKey=${{ secrets.OPENAI_API_KEY }} \
          --set openaiOrganization=$OPENAI_ORGANIZATION \
          --set brokerUrl=$BROKER_URL

    # IMPORTANT: Service must be named something else than 'flower'.
    # Naming it simply 'flower' can lead to conflicts as detailed in this issue:
    # https://github.com/mher/flower/issues/738#issuecomment-330606229
    # To avoid such conflicts, the service is named 'celery-flower' instead.
    - name: Deploy Flower (Celery Monitoring Tool)
      run: |-
        helm upgrade --install celery-flower ./charts/flower \
          --set image=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA \
          --set openaiApiKey=${{ secrets.OPENAI_API_KEY }} \
          --set openaiOrganization=$OPENAI_ORGANIZATION \
          --set brokerUrl=$BROKER_URL
